name: UltimateCosmetics
main: com.j0ach1mmall3.ultimatecosmetics.Main
version: 4.2.0
author: j0ach1mmall3
description: Featuring over 20 different Cosmetics Types, endless possibilities!
depend: [JLib]
softdepend: [LibsDisguises, ProtocolLib]
commands:
    UltimateCosmetics:
        description: Main UltimateCosmetics command
        usage: /<command> <arguments>
        aliases: uc
    Stacker:
        description: Toggle Stacker
        usage: /<command>
        aliases: togglestacker
    Upsidedown:
        description: Toggle Upsidedown
        usage: /<command>
        aliases: flip
    Ears:
        description: Toggle Ears
        usage: /<command>
    GiveAmmo:
        description: Give Gadget Ammo to a player
        usage: /<command> <player> <gadget> <amount>
    RemoveAmmo:
        description: Remove Gadget Ammo from a player
        usage: /<command> <player> <gadget> <amount>
    RemoveAllCosmetics:
        description: Removes all Cosmetics from a player
        usage: /<command> <player>
    GiveCosmetic:
        description: Give a Cosmetic to a player
        usage: /<command> <player> <cosmetictype> <cosmetic>
    RemoveCosmetic:
        description: Remove a player's Cosmetic
        usage: /<command> <player> <cosmetictype>
permissions:
    uc.*:
        description: All the UltimateCosmetics permissions
        default: op
        children:
            uc.reload: true
            uc.openmenu: true
            uc.debug: true
            uc.renamepet: true
            uc.giveammo: true
            uc.removeammo: true
            uc.removeallcosmetics: true
            uc.stacker: true
            uc.unlimitedammo: true
            uc.givecosmetic: true
            uc.removecosmetic: true
    uc.givecosmetic:
        description: Access to giving Cosmetic Types
        default: op
    uc.removecosmetic:
        description: Access to removing Cosmetic Types
        default: op
    uc.reload:
        description: Access to /uc reload
        default: op
    uc.openmenu:
        description: Access to /uc openmenu
        default: op
    uc.debug:
        description: Access to /uc debug
        default: op
    uc.renamepet:
        description: Access to renaming your Pet
        default: op
    uc.giveammo:
        description: Access to /giveammo
        default: op
    uc.removeammo:
        description: Access to /removeammo
        default: op
    uc.removeallcosmetics:
        description: Access to /removeallcosmetics
        default: op
    uc.stacker:
        description: Access to /stacker
        default: true
    uc.unlimitedammo:
        description: Unlimited Ammo for Gadgets
        default: op