# ######################################################################################## #
# UltimateCosmetics version 4.X.X configuration                                            #
# Any help with this configuration should be requested here:                               #
# https://www.spigotmc.org/threads/ultimatecosmetics.60528/                                #
# (c) 2016 j0ach1mmall3 - All rights reserved                                              #
# ######################################################################################## #

# Should the plugin check for updates on Spigot
UpdateChecker: true
# The logging level, can be ALL, EXTENDED, NORMAL, MINIMAL, NOTHING
LogLevel: EXTENDED
# Should Cosmetics be removed when a player changes worlds?
RemoveCosmeticsOnWorldChange: false
# Should Cosmetics be removed when a player logs out?
RemoveCosmeticsOnLogOut: false
# The worlds in which this plugin will not work
# Make sure RemoveCosmeticsOnWorldChange is set to true for this to work correctly
WorldsBlacklist:
- someworld
- someotherworld
# Should Bat sounds be completely disabled on the server?
DisableBatSounds: true
# Should an Item be given upon joining, that will display the GUI upon clicking? (It is advised to turn this off in a non-hub environment)
GiveItemOnJoin: true
JoinItem:
    # The item format of the item (More info here: https://github.com/j0ach1mmall3/JLib/wiki/The-new-Item-Format)
    Item: '54 name:&1C&2o&3s&4m&5e&6t&7i&8c&9s lore:&7&oAmazing_Cosmetics!'
    # The slot in which the item will be put
    Position: 3
# The Sound to be played when a player opens the GUI (leave blank for no sound) A list of valid sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
GUIOpenSound: BLOCK_CHEST_OPEN
# The Sound to be played when a player clicks in the GUI (leave blank for no sound) A list of valid sounds can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
GUIClickSound: UI_BUTTON_CLICK
# The command that will open the Cosmetics GUI
CosmeticsCommand: /cosmetics
CosmeticsGUI:
    # The inventory name of the Cosmetics GUI
    Name: '&1C&2o&3s&4m&5e&6t&7i&8c&9s'
    # The size of the Cosmetics GUI (must be divisible by 9!)
    Size: 45
    Items:
        AurasItem:
            # The item format of the item
            Item: '95:14 name:&1&lAuras lore:&7&oShow_everyone_who''s_important!'
            # The position in the GUI of this item (starts at 0)
            Position: 1
            #The command to be executed when you click on the item. Generally, this is the same command as defined in the Cosmetic's config, however, there are plenty of other options.
            Command: /auras
        BalloonsItem:
            Item: '420 name:&2&lBalloons lore:&7&oGet_yourself_a_lovely_Balloon!'
            Position: 3
            Command: /balloons
        BannerCapesItem:
            Item: '425:8 name:&3&lBanner_Capes lore:&7&oWalk_around_with_a_stylish_Cape! pattern_cross:red'
            Position: 5
            Command: /bannercapes
        BannersItem:
            Item: '425:3 name:&4&lBanners lore:&7&oPut_an_amazing_Banner_on_your_head! pattern_creeper:blue'
            Position: 7
            Command: /banners
        BlockPetsItem:
            Item: '91 name:&5&lBlock_Pets lore:&7&oBefriend_the_Blocks!'
            Position: 9
            Command: /blockpets
        BowTrailsItem:
            Item: '261 name:&6&lBowtrails lore:&7&oKill_your_opponents_in_style!'
            Position: 11
            Command: /bowtrails
        CloaksItem:
            Item: '116 name:&7&lCloaks lore:&7&oEquip_yourself_some_mystical_Cloaks!'
            Position: 15
            Command: /cloaks
        FireworksItem:
            Item: '401 name:&8&lFireworks lore:&7&oLight_off_some_celebration_Fireworks!'
            Position: 17
            Command: /fireworks
        GadgetsItem:
            Item: '369 name:&9&lGadgets lore:&7&oGet_hold_of_some_cool_Gadgets!'
            Position: 21
            Command: /gadgets
        HatsItem:
            Item: '310 name:&a&lHats lore:&7&oShow_the_world_your_new_Hats!'
            Position: 23
            Command: /hats
        HeartsItem:
            Item: '351:1 name:&b&lHearts lore:&7&oCustomize_your_Hearts!'
            Position: 27
            Command: /hearts
        MorphsItem:
            Item: '397:4 name:&c&lMorphs lore:&7&oScare_your_friends_as_a_Creeper!'
            Position: 29
            Command: /morphs
        MountsItem:
            Item: '329 name:&d&lMounts lore:&7&oBecause_walking_is_mainstream!'
            Position: 33
            Command: /mounts
        MusicItem:
            Item: '2258 name:&1&lMusic lore:&7&oListen_to_some_funky_Music!'
            Position: 35
            Command: /music
        ParticlesItem:
            Item: '399 name:&2&lParticles lore:&7&oLet_Particles_fly_around_you!'
            Position: 37
            Command: /particles
        PetsItem:
            Item: '383 name:&3&lPets lore:&7&oFriends_for_life! entitytype:pig'
            Position: 39
            Command: /pets
        TrailsItem:
            Item: '362 name:&4&lTrails lore:&7&oLeave_a_trail_of..._Anything!'
            Position: 41
            Command: /trails
        WardrobeItem:
            Item: '299 name:&5&lWardrobe lore:&7&oShow_off_some_beautiful_clothes!'
            Position: 43
            Command: /wardrobe
# Which Cosmetics should be enabled
Cosmetics:
  # Requires MC 1.9 or above
  Auras: true
  # Requires MC 1.4 or above
  Balloons: true
  # Requires MC 1.8 or above
  BannerCapes: true
  # Requires MC 1.8 or above
  Banners: true
  # Requires MC 1.4 or above
  BlockPets: true
  # Requires MC 1.7 or above
  BowTrails: true
  # Requires MC 1.7 or above
  Cloaks: true
  # Requires MC 1.4 or above
  Fireworks: true
  # Requires MC 1.4 or above
  Gadgets: true
  # Requires MC 1.4 or above
  Hats: true
  # Requires MC 1.4 or above
  Hearts: true
  # Requires LibsDisguises & MC 1.4 or above
  Morphs: true
  # Requires MC 1.4 or above
  Mounts: true
  # Requires MC 1.4 or above
  Music: true
  # Requires MC 1.7 or above
  Particles: true
  # Requires MC 1.4 or above
  Pets: true
  # Requires MC 1.4 or above
  Trails: true
  # Requires MC 1.4 or above
  Wardrobe: true
DoNotChange: 4.1.3